### ISSUE TITLE
costs summary a bit confusing to understand

### ISSUE THREAD

**Issue by musm** [kimikage/CodeCosts.jl#9]
![image](https://user-images.githubusercontent.com/4319522/91672770-4d700080-eafe-11ea-80ff-fc77457364fa.png)

It looks like `=` represent the cost number.

Wouldn't it just be better to use  █   or just `=` without the printing of the number, so that it's actually a histogram

**Comment by kimikage** [comment]
When thinking about inlining, there is an important difference between having two cost "2" and one cost "4". Therefore, I think that some kind of separator is necessary. In the current implementation, the number is both a label and a separator.

I made the decision not to use non-ascii characters (at least in the default implementation) because they can cause problems with monospace rendering. (In fact, I use some Japanese fonts and run into such problems.) I had tried several other ascii characters (e.g. `#`, `:`, `>`, `-`, `_`) and found `=` to be the best for me.

> It looks like = represent the cost number.

Strictly speaking, the cost number is expressed as the number of both decimal characters and `=`.  The cost "5" has "four" `=` s and the cost "20" has "eighteen" `=`s. I think the printing is actually a histogram.
```
5====5====5====5====
20==================
```

Of course, there is room for improvement in the display and several customization options can be added. :smile:

**Comment by kimikage** [comment]
BTW, at the conception stage, I also had the following idea.
```
 5 | |||||
20 | 5===|5===|5===|3=|2|
20 | 20=================|
```

I thought about specifying a background color with the ANSI escape codes, but it was too much of a bother to find the corresponding color codes, so I gave up.
